# Dockerfile para o desafio "fonte-secreta"

# Usar uma imagem oficial e leve do Nginx
FROM nginx:alpine

# Copia o arquivo do desafio para o diretório padrão do Nginx
COPY ./index.html /usr/share/nginx/html/index.html